from typing import Protocol


class CacheService(Protocol):
    def get(self, key: str) -> bytes | None: ...
    def set(self, key: str, value: bytes, ttl: int) -> None: ...
    def invalidate_prefix(self, prefix: str) -> None: ...