"""add session_speaker_link table

Revision ID: 18c20bbc0065
Revises: a2367347c07e
Create Date: 2026-05-09 21:38:45.614970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18c20bbc0065'
down_revision: Union[str, None] = 'a2367347c07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_speaker_link',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'speaker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_speaker_link')
    # ### end Alembic commands ###
